### ISSUE TITLE
wrong link to Lithology docs

### ISSUE THREAD

**Issue by speleophysics** [landlab/tutorials#36]
In the Lithology and LithoLayers tutorial the link to the full Litholayers documentation is incorrect. It points to layers.litholayers. I think it should be components.litholayers.

**Comment by kbarnhart** [comment]
@speleophysics thanks for catching that. Looks like some of the other links to the landlab docs are broken too. PR fixing those forthcoming. 

This issue is associated with [the JOSS review](https://github.com/openjournals/joss-reviews/issues/979) of this submodule.
