### ISSUE TITLE
Is topographic__gradient really an input field in making_components.ipynb?

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/tutorials#5]
In the component making tutorial, `topographic__gradient` doesn’t appear to be an input field. I say that because:
1. It’s created if it’s missing.
2. Even if it isn’t missing, it automatically gets immediately overwritten during instantiation with a new set of values.

That sounds like an output field to me, not an input field. It might be ambiguous if there was some testing performed to use the values if provided but to calculate gradients if not, but that's not happening. Ergo, this is a straight-up output field as written.

Probably needs to be fixed by @gregtucker, as he wrote this and it feels a bit cheeky just to change.

**Comment by gregtucker** [comment]
Made topographic__gradient an output var.
