### ISSUE TITLE
Unexpanded and Python script tutorials

### ISSUE THREAD

**Issue by mcflugen** [landlab/tutorials#9]
In most of the tutorial folders we have three versions of each tutorial. Two are Jupyter notebooks that should be the same except one is unexpanded (ends in `_unexpanded.ipynb`) and the other expanded. The third is the notebook saved as a `.py` file.

I propose we get rid of the `_unexpanded.ipynb` and `.py` files and just keep a single version of the tutorial in our repository. The main reasons being it's easier to maintain one version and reduces the risk of the three files falling out of sync.

What do folks think?

**Comment by nicgaspar** [comment]
My initial gut reaction is that we should get rid of the expanded version. That way people can download and run without seeing the answer first. Maybe I'm over thinking it, but the process of running each cell and seeing what comes out is satisfying. On the flip side, it's nice to just view these on github and see what different commands do.

I thought that we were leaving the .py for testing purposes? Is that not correct?

**Comment by mcflugen** [comment]
As long as there is only one version of the notebooks, I think that's fine. I believe there are places where we link to the notebooks so that people can view them online, without actually downloading them. That may be the reason we have expanded versions.

For the tutorial-testing framework I automatically convert the notebooks to scripts that are then tested. As such, we don't need to keep them in the repository (at least for that reason).

**Comment by nicgaspar** [comment]
OK, let's leave the expanded versions then.

I should have known that your testing framework is more sophisticated than I imagined.

**Comment by mcflugen** [comment]
OK. I can do that and it would be easy to switch to unexpanded versions if that's what we decide later. Using the expanded versions also is nice because we don't have to always remember to save unexpanded versions before committing changes.
